# Generated by Django 3.2.4 on 2021-06-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='airplane_id',
            field=models.CharField(default=1, max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='airplane_model',
            field=models.CharField(default='777', max_length=200),
        ),
        migrations.AddField(
            model_name='document',
            name='airplane_name',
            field=models.CharField(default='airplane', max_length=200),
        ),
    ]
