# Generated by Django 3.2.4 on 2021-06-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_document_airplane_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='airplane_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='airplane_model',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='document',
            name='airplane_name',
            field=models.CharField(max_length=200),
        ),
    ]
