# Generated by Django 3.2.4 on 2021-06-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210614_1559'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airplane_name', models.CharField(max_length=200)),
                ('airplane_model', models.CharField(max_length=200)),
                ('airplane_id', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='airplane_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='airplane_model',
        ),
        migrations.RemoveField(
            model_name='document',
            name='airplane_name',
        ),
    ]
